name: bhansa's blog
description: Thoughts, projects and lot more...
meta_description: "bhansa's blog(Bharat Saraswat), writing about python projects, django and lots of other things"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'https://bhansa.github.io/' #should start with a / (critical)
domain_name: 'https://bhansa.github.io'
google_analytics: 'UA-80356944-1'
plugins: [jekyll-paginate]


# Details for the RSS feed generator
url:            'https://bhansa.github.io'
author:         'Bharat Saraswat'
